name: Build Xposed APK

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install JDK 17 for sdkmanager
      - name: Set up JDK 17 for Android tools
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # This will set JAVA_HOME for sdkmanager

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Switch to JDK 8 for legacy project build
      - name: Set up JDK 8 for build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Check for Gradle
        id: gradle_check
        run: |
          if [ -f "./gradlew" ] || [ -f "./build.gradle" ]; then
            echo "has_gradle=true" >> $GITHUB_ENV
          else
            echo "has_gradle=false" >> $GITHUB_ENV
          fi

      - name: Build with Gradle (if exists)
        if: env.has_gradle == 'true'
        run: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --stacktrace || ./gradlew build --stacktrace

      - name: Build with Ant (fallback)
        if: env.has_gradle == 'false'
        run: |
          if [ ! -f "build.xml" ]; then
            android update project -p . --target android-19
          fi
          ant debug

      - name: Find APK
        id: find_apk
        run: |
          apk_file=$(find . -type f -name "*.apk" | head -n 1)
          echo "apk_file=$apk_file" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Xposed-Module-APK
          path: ${{ steps.find_apk.outputs.apk_file }}