name: Build Xposed APK

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install JDK 17 for sdkmanager
      - name: Set up JDK 17 for Android tools
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Download legacy tools that include the 'android' command
      - name: Install legacy Android tools (for Ant support)
        run: |
          wget https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
          unzip -qo tools_r25.2.5-linux.zip
          mv tools $ANDROID_HOME/legacy-tools

      # Switch to JDK 8 for build
      - name: Set up JDK 8 for build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Ant (legacy)
        if: env.has_gradle == 'false'
        env:
          PATH: ${{ env.ANDROID_HOME }}/legacy-tools:$PATH
        run: |
          if [ ! -f "build.xml" ]; then
            android update project -p . --target android-19
          fi
          ant debug

      - name: Find APK
        id: find_apk
        run: |
          apk_file=$(find . -type f -name "*.apk" | head -n 1)
          echo "apk_file=$apk_file" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Xposed-Module-APK
          path: ${{ steps.find_apk.outputs.apk_file }}